name: Capstone Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:23
    steps:
      - uses: action/checkout@v3
        with:
          node-version: 23
      - run: npm ci
      - run: npm test
      - run: npm run build